# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image.proto',
  package='',
  syntax='proto3',
  serialized_options=b'P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bimage.proto\"E\n\x07NLImage\x12\r\n\x05\x63olor\x18\x01 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\"\xb0\x01\n\x14NLImageRotateRequest\x12\x30\n\x08rotation\x18\x01 \x01(\x0e\x32\x1e.NLImageRotateRequest.Rotation\x12\x17\n\x05image\x18\x02 \x01(\x0b\x32\x08.NLImage\"M\n\x08Rotation\x12\x08\n\x04NONE\x10\x00\x12\x0e\n\nNINETY_DEG\x10\x01\x12\x12\n\x0eONE_EIGHTY_DEG\x10\x02\x12\x13\n\x0fTWO_SEVENTY_DEG\x10\x03\x32\x62\n\x0eNLImageService\x12.\n\x0bRotateImage\x12\x15.NLImageRotateRequest\x1a\x08.NLImage\x12 \n\nMeanFilter\x12\x08.NLImage\x1a\x08.NLImageB\x02P\x01\x62\x06proto3'
)



_NLIMAGEROTATEREQUEST_ROTATION = _descriptor.EnumDescriptor(
  name='Rotation',
  full_name='NLImageRotateRequest.Rotation',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NINETY_DEG', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ONE_EIGHTY_DEG', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='TWO_SEVENTY_DEG', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=186,
  serialized_end=263,
)
_sym_db.RegisterEnumDescriptor(_NLIMAGEROTATEREQUEST_ROTATION)


_NLIMAGE = _descriptor.Descriptor(
  name='NLImage',
  full_name='NLImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='color', full_name='NLImage.color', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='NLImage.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='width', full_name='NLImage.width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='NLImage.height', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=84,
)


_NLIMAGEROTATEREQUEST = _descriptor.Descriptor(
  name='NLImageRotateRequest',
  full_name='NLImageRotateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rotation', full_name='NLImageRotateRequest.rotation', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='image', full_name='NLImageRotateRequest.image', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NLIMAGEROTATEREQUEST_ROTATION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=263,
)

_NLIMAGEROTATEREQUEST.fields_by_name['rotation'].enum_type = _NLIMAGEROTATEREQUEST_ROTATION
_NLIMAGEROTATEREQUEST.fields_by_name['image'].message_type = _NLIMAGE
_NLIMAGEROTATEREQUEST_ROTATION.containing_type = _NLIMAGEROTATEREQUEST
DESCRIPTOR.message_types_by_name['NLImage'] = _NLIMAGE
DESCRIPTOR.message_types_by_name['NLImageRotateRequest'] = _NLIMAGEROTATEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NLImage = _reflection.GeneratedProtocolMessageType('NLImage', (_message.Message,), {
  'DESCRIPTOR' : _NLIMAGE,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:NLImage)
  })
_sym_db.RegisterMessage(NLImage)

NLImageRotateRequest = _reflection.GeneratedProtocolMessageType('NLImageRotateRequest', (_message.Message,), {
  'DESCRIPTOR' : _NLIMAGEROTATEREQUEST,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:NLImageRotateRequest)
  })
_sym_db.RegisterMessage(NLImageRotateRequest)


DESCRIPTOR._options = None

_NLIMAGESERVICE = _descriptor.ServiceDescriptor(
  name='NLImageService',
  full_name='NLImageService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=265,
  serialized_end=363,
  methods=[
  _descriptor.MethodDescriptor(
    name='RotateImage',
    full_name='NLImageService.RotateImage',
    index=0,
    containing_service=None,
    input_type=_NLIMAGEROTATEREQUEST,
    output_type=_NLIMAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='MeanFilter',
    full_name='NLImageService.MeanFilter',
    index=1,
    containing_service=None,
    input_type=_NLIMAGE,
    output_type=_NLIMAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NLIMAGESERVICE)

DESCRIPTOR.services_by_name['NLImageService'] = _NLIMAGESERVICE

# @@protoc_insertion_point(module_scope)
